### ISSUE TITLE
Exercícios HTML #Week1 #1

### ISSUE THREAD

**Issue by Josue23** [WoMakersCode/summer-training-week#3]
Olá @cyz e @cynthiapereira,
eu posso fazer um fork desse repositório e fazer um pull request com a minha solução do exercício?

Abs.

Josué

**Comment by cyz** [comment]
@Josue23 Pode fazer :) Não irei aprovar seu PR para não expor diretamente sua solução, mas irei avaliar, ok?

**Comment by Josue23** [comment]
Obrigado,
vou fazer o fork e o PR.

:-)
